apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-trino-ingress
  namespace: default
  labels:
    app: trino
  annotations:
    # Ingress Core Settings
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: instance
    # Health Check Settings
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
#Important Note:  Need to add health check path annotations in service level if we are planning to use multiple targets in a load balancer    
    #alb.ingress.kubernetes.io/healthcheck-path: /usermgmt/health-status
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '35'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '30'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:091021251638:certificate/bd9ca0f1-b75c-4310-9429-42f48680a1fe
    alb.ingress.kubernetes.io/subnets: subnet-0dffb9404032c75fb, subnet-07a139bbf2274555f
    alb.ingress.kubernetes.io/success-codes: '303'
    alb.ingress.kubernetes.io/security-groups: sg-0793fff08492e6c1c, sg-073ad50379141bf30
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '10'
spec:
  rules:
  - host: 
    http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: my-trino
                port:
                  number: 8080                      
